correct = "Correct!"
results = "Your results:"
give_up_page_msg = "Correct book:"
give_up_button_msg = "Don't know"
next_button_msg = "Next"
check_button_msg = "Check"
input_placeholder = "Enter title"
help1_button_msg = "Ganre"
help2_button_msg = "Author"
