correct = "Dobrze!"
results = "Wyniki końcowe:"
give_up_page_msg = "Twoja książka to:"
give_up_button_msg = "Nie wiem"
next_button_msg = "Dalej"
check_button_msg = "Sprawdź"
input_placeholder = "Wpisz tytuł"
help1_button_msg = "Gatunek"
help2_button_msg = "Autor"
